### ISSUE TITLE
[Bug]: number of days in month of 2081 is not correct

### ISSUE THREAD

**Issue by novaprime-code** [anuzpandey/laravel-nepali-date#11]
### What happened?

When trying to convert date 2081-02-32 to AD date i am getting error
and when explored the array of number of days in months are mistake

 code: Carbon::parse($request->startDate)->toEnglishDate();

### How to reproduce the bug

Try to change the date 2081-02-32 to AD

### Package Version

1.6

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

Linux

### Notes

2081:[[31,31,32,32,31,30,30,30,29,30,30,30]  =>  this is incorrect 
it should be
2081 : [31, 32, 31, 32, 31, 30, 30, 30, 29, 30, 29, 31],

please check and update

**Comment by anuzpandey** [comment]
Hi. The update for date-picker is live. Fixes are on the way for this package too. 😀
